package main

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"sort"
	"strings"
)

const generatedHeader = "// Code generated by conduit-gen. DO NOT EDIT.\n"

func isGenerated(data []byte) bool { return bytes.HasPrefix(data, []byte(generatedHeader)) }

type emitter struct {
	pkg     *types.Package
	body    bytes.Buffer
	imports map[string]string
}

func generate(pkg *types.Package, name string) ([]byte, error) {
	m := &model{pkg: pkg, types: map[string]*topology{}, active: map[string]bool{}}
	if _, err := m.topology(name); err != nil {
		return nil, err
	}
	names := make([]string, 0, len(m.types))
	for name := range m.types {
		names = append(names, name)
	}
	sort.Strings(names)
	e := &emitter{pkg: pkg, imports: map[string]string{}}
	// Reserve stable conventional import names before printing arbitrary types.
	for _, p := range []string{"context", "fmt", "path/filepath", modulePath + "/layout", modulePath + "/mgmt"} {
		parts := strings.Split(p, "/")
		e.imports[p] = parts[len(parts)-1]
	}
	symbols := map[string]bool{}
	claim := func(name string) error {
		if symbols[name] || pkg.Scope().Lookup(name) != nil {
			return fmt.Errorf("generated identifier %s conflicts with another declaration", name)
		}
		symbols[name] = true
		return nil
	}
	for _, name := range names {
		t := m.types[name]
		for _, symbol := range []string{t.generated, "Bind" + t.generated, "wrap" + t.generated} {
			if err := claim(symbol); err != nil {
				return nil, err
			}
		}
		if t.root.kind != "Scope" {
			if err := claim("New" + t.generated); err != nil {
				return nil, err
			}
		}
		reserved := map[string]bool{"Layout": true, "Binding": true, "Capabilities": true, "Root": true}
		for _, op := range t.root.ops {
			reserved[methodName(op)] = true
		}
		for _, f := range t.fields {
			if f == t.root {
				continue
			}
			if reserved[f.name] {
				return nil, fmt.Errorf("%s.%s conflicts with a generated controller method", t.name, f.name)
			}
			if f.kind != "Topology" {
				if err := claim(f.generated); err != nil {
					return nil, err
				}
				if f.kind == "Collection" && contains(f.ops, "create") {
					if err := claim(f.generated + "Created"); err != nil {
						return nil, err
					}
				}
			}
		}
		e.topology(t)
	}
	var out bytes.Buffer
	out.WriteString(generatedHeader)
	fmt.Fprintf(&out, "\npackage %s\n\nimport (\n", pkg.Name())
	paths := make([]string, 0, len(e.imports))
	for path, alias := range e.imports {
		// Some topology shapes do not need context, fmt, or filepath.
		if bytes.Contains(e.body.Bytes(), []byte(alias+".")) {
			paths = append(paths, path)
		}
	}
	sort.Strings(paths)
	for _, path := range paths {
		fmt.Fprintf(&out, "%s %q\n", e.imports[path], path)
	}
	out.WriteString(")\n\n")
	out.Write(e.body.Bytes())
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}

func (e *emitter) p(format string, args ...any) { fmt.Fprintf(&e.body, format+"\n", args...) }
func (e *emitter) typ(t types.Type) string {
	return types.TypeString(t, func(pkg *types.Package) string {
		if pkg.Path() == e.pkg.Path() {
			return ""
		}
		if alias, ok := e.imports[pkg.Path()]; ok {
			return alias
		}
		alias := pkg.Name()
		used := func(a string) bool {
			for _, v := range e.imports {
				if v == a {
					return true
				}
			}
			return false
		}
		for i := 2; used(alias); i++ {
			alias = fmt.Sprintf("%s%d", pkg.Name(), i)
		}
		e.imports[pkg.Path()] = alias
		return alias
	})
}

func (e *emitter) topology(t *topology) {
	name, layoutType, rootKind := t.generated, e.typ(t.layout), t.root.kind
	e.p("// %s binds the topology declared by %s to shared layout state.", name, t.name)
	e.p("type %s struct {", name)
	e.p("core mgmt.%s[%s]", rootKind, layoutType)
	for _, f := range t.fields {
		if f == t.root {
			continue
		}
		fieldType := f.generated
		if f.kind == "Topology" {
			fieldType = f.topology.generated
		}
		e.p("%s *%s", f.name, fieldType)
	}
	e.p("}\n")
	e.p("func (v *%s) Layout() *%s { return v.core.Layout() }", name, layoutType)
	e.bindingMethods(name, "v.core", t.root.ops)
	if rootKind != "Scope" {
		e.p("func (v *%s) Root() layout.Dir { return v.core.Root() }", name)
		e.p("// New%s composes a fresh layout once without creating filesystem content.", name)
		e.p("func New%s(root string, options mgmt.%sOptions) (*%s,error) {", name, rootKind, name)
		e.p("absolute,err := filepath.Abs(root); if err != nil { return nil,err }")
		e.p("tree := new(%s)", layoutType)
		e.p("if err := layout.Compose(absolute,tree); err != nil { return nil,err }")
		e.p("return Bind%s(layout.NewDir(absolute),tree,options)\n}", name)
	}
	e.p("// Bind%s retains the supplied composed layout and any cached edits.", name)
	if rootKind == "Scope" {
		e.p("func Bind%s(owner mgmt.Bound, tree *%s, options mgmt.ScopeOptions) (*%s,error) {", name, layoutType, name)
		e.p("core,err := mgmt.BindScope(owner,tree,options)")
	} else {
		e.p("func Bind%s(root layout.Dir, tree *%s, options mgmt.%sOptions) (*%s,error) {", name, layoutType, rootKind, name)
		e.p("core,err := mgmt.Bind%s(root,tree,options)", rootKind)
	}
	e.p("if err != nil { return nil,err }; return wrap%s(core)\n}", name)
	e.p("func wrap%s(core mgmt.%s[%s]) (*%s,error) {", name, rootKind, layoutType, name)
	e.p("v := &%s{core:core}", name)
	for _, f := range t.fields {
		if f != t.root {
			e.bindField(t, f)
		}
	}
	e.p("return v,nil\n}\n")
	rootTarget := "v.core"
	if rootKind != "Scope" {
		rootTarget += ".Scope()"
	}
	e.scopeMethods(name, rootTarget, t.root)
	for _, f := range t.fields {
		if f == t.root || f.kind == "Topology" {
			continue
		}
		e.fieldType(f)
	}
}

func (e *emitter) bindingMethods(name, target string, ops []string) {
	e.p("func (v *%s) Binding() mgmt.Binding { return %s.Binding() }", name, target)
	// Applicability comes from runtime; a generated restriction can only narrow it.
	e.p("func (v *%s) Capabilities() mgmt.Capabilities {", name)
	e.p("allowed := map[mgmt.Operation]bool{")
	for _, op := range ops {
		e.p("mgmt.Operation(%q):true,", op)
	}
	e.p("}; var result mgmt.Capabilities")
	e.p("for _, op := range %s.Capabilities() { if allowed[op] { result = append(result,op) } }; return result\n}", target)
}

func (e *emitter) bindField(t *topology, f *field) {
	owner := "v.core"
	if f.owner != t.root {
		owner = "v." + f.owner.name + ".core"
	}
	bound := owner + ".Layout()"
	if f.bind != "." {
		var path string
		for _, part := range strings.Split(f.bind, ".") {
			if path != "" {
				path += "."
			}
			path += part
			selected, _ := boundType(f.owner.value, path)
			if _, pointer := types.Unalias(selected).(*types.Pointer); pointer {
				e.p("if %s.%s == nil { return nil,fmt.Errorf(%q) }", bound, path, t.name+"."+f.name+": nil layout field "+path)
			}
		}
		bound += "." + f.bind
	}
	ptr := bound
	if f.bind != "." {
		if _, ok := types.Unalias(f.bound).(*types.Pointer); !ok {
			ptr = "&" + bound
		}
	}
	coreName := "bound" + f.name
	switch f.kind {
	case "Scope":
		e.p("%s,err := mgmt.BindScope(%s,%s,mgmt.ScopeOptions{})", coreName, owner, ptr)
	case "Space":
		root, _ := layoutRoot(f.value)
		e.p("%s,err := mgmt.BindSubspace(%s,%s.%s,%s,mgmt.SpaceOptions{})", coreName, owner, bound, root, ptr)
	case "Document":
		e.p("%s,err := mgmt.BindDocument[%s](%s,%s,mgmt.DocumentOptions[%s]{})", coreName, e.typ(f.value), owner, ptr, e.typ(f.value))
	case "Collection":
		e.p("%s,err := mgmt.BindCollection(%s,%s,mgmt.CollectionOptions{})", coreName, owner, ptr)
	case "Topology":
		if f.topology.root.kind == "Space" {
			root, _ := layoutRoot(f.value)
			e.p("%s,err := mgmt.BindSubspace(%s,%s.%s,%s,mgmt.SpaceOptions{})", coreName, owner, bound, root, ptr)
		} else {
			e.p("%s,err := mgmt.BindScope(%s,%s,mgmt.ScopeOptions{})", coreName, owner, ptr)
		}
	}
	e.p("if err != nil { return nil,fmt.Errorf(%q,err) }", t.name+"."+f.name+": %w")
	if f.kind == "Topology" {
		e.p("v.%s,err = wrap%s(%s)", f.name, f.topology.generated, coreName)
		e.p("if err != nil { return nil,fmt.Errorf(%q,err) }", t.name+"."+f.name+": %w")
	} else {
		e.p("v.%s = &%s{core:%s}", f.name, f.generated, coreName)
	}
}

func (e *emitter) fieldType(f *field) {
	name, value := f.generated, e.typ(f.value)
	e.p("// %s is the declared %s handle. Operations delegate to mgmt.", name, strings.ToLower(f.kind))
	e.p("type %s struct { core mgmt.%s[%s] }", name, f.kind, value)
	e.bindingMethods(name, "v.core", f.ops)
	switch f.kind {
	case "Scope", "Space":
		e.p("func (v *%s) Layout() *%s { return v.core.Layout() }", name, value)
		target := "v.core"
		if f.kind == "Space" {
			e.p("func (v *%s) Root() layout.Dir { return v.core.Root() }", name)
			target += ".Scope()"
		}
		e.scopeMethods(name, target, f)
	case "Document":
		for _, op := range f.ops {
			switch op {
			case "read":
				e.p("func (v *%s) Read(ctx context.Context, policy mgmt.ReadPolicy) (%s,error) { return v.core.Read(ctx,policy) }", name, value)
			case "update":
				e.p("func (v *%s) Update(ctx context.Context, edit func(*%s) error, policy mgmt.UpdatePolicy) (mgmt.Outcome,error) { return v.core.Update(ctx,edit,policy) }", name, value)
			default:
				e.standardMethod(name, "v.core", op)
			}
		}
	case "Collection":
		for _, op := range f.ops {
			switch op {
			case "list":
				e.p("func (v *%s) List(ctx context.Context, policy mgmt.ListPolicy) (mgmt.Inventory,error) { return v.core.List(ctx,policy) }", name)
			case "at":
				e.p("func (v *%s) At(key string, policy mgmt.BindPolicy) (*%s,error) {", name, f.topology.generated)
				e.p("core,err := v.core.At(key,policy); if err != nil { return nil,err }; return wrap%s(core)\n}", f.topology.generated)
			case "create":
				e.p("// %sCreated retains the member handle and partial outcome even when creation fails.", name)
				e.p("type %sCreated struct { Value *%s; Outcome mgmt.Outcome }", name, f.topology.generated)
				e.p("func (v *%s) Create(ctx context.Context,key string,input %s,policy mgmt.CreatePolicy) (%sCreated,error) {", name, e.typ(f.creation.input), name)
				e.p("created,err := mgmt.Create(ctx,v.core,key,input,%s,policy)", f.creation.name)
				e.p("result := %sCreated{Outcome:created.Outcome}", name)
				e.p("if created.Value != nil { var bindErr error; result.Value,bindErr = wrap%s(created.Value); if bindErr != nil {", f.topology.generated)
				e.p("if err != nil { return result,fmt.Errorf(\"creation: %%w; binding created member: %%w\",err,bindErr) }; return result,bindErr } }")
				e.p("return result,err\n}")
			}
		}
	}
	e.p("")
}

func (e *emitter) scopeMethods(name, target string, f *field) {
	for _, op := range f.ops {
		switch op {
		case "detect":
			e.p("func (v *%s) Detect(ctx context.Context, policy mgmt.DetectionPolicy) (mgmt.Detection,error) { return v.core.Detect(ctx,policy) }", name)
		case "bootstrap":
			if f.bootstrap == nil {
				e.p("func (v *%s) Bootstrap(ctx context.Context, policy mgmt.BootstrapPolicy) (mgmt.Outcome,error) {", name)
				e.p("return mgmt.Bootstrap(ctx,%s,struct{}{},mgmt.Initialization[%s,struct{}]{},policy)\n}", target, e.typ(f.value))
			} else {
				e.p("func (v *%s) Bootstrap(ctx context.Context,input %s,policy mgmt.BootstrapPolicy) (mgmt.Outcome,error) { return mgmt.Bootstrap(ctx,%s,input,%s,policy) }", name, e.typ(f.bootstrap.input), target, f.bootstrap.name)
			}
		default:
			e.standardMethod(name, target, op)
		}
	}
}

func (e *emitter) standardMethod(name, target, op string) {
	policy := methodName(op) + "Policy"
	result := "Outcome"
	switch op {
	case "inspect":
		policy, result = "InspectionPolicy", "Inventory"
	case "validate":
		policy, result = "ValidationPolicy", "Diagnostics"
	}
	e.p("func (v *%s) %s(ctx context.Context, policy mgmt.%s) (mgmt.%s,error) { return %s.%s(ctx,policy) }", name, methodName(op), policy, result, target, methodName(op))
}

func methodName(op string) string {
	if op == "" {
		return ""
	}
	return strings.ToUpper(op[:1]) + op[1:]
}
func contains(values []string, value string) bool {
	for _, v := range values {
		if v == value {
			return true
		}
	}
	return false
}
