version: '3'

tasks:
  default:
    cmds:
      - task -l

  # ==
  # GO
  # ==

  install:
    desc: Install all Go module dependencies
    cmds:
      - go mod download
      - go mod tidy
      - go mod verify

  validate:
    desc: Validate all Go modules
    cmds:
      - gofmt -w -s ./layout ./formats
      - go test ./layout ./formats
      - go vet ./layout ./formats

  # ========
  # Workflow
  # ========

  go:
    desc: Enter an interactive dev shell
    cmds:
      - shade enter go
  code:
    desc: Open OpenCode in the devshell
    cmds:
      - shade enter opencode
