// Code generated by conduit-gen. DO NOT EDIT.

package management

import (
	context "context"
	fmt "fmt"
	layout "github.com/qlustra/conduit/layout"
	mgmt "github.com/qlustra/conduit/mgmt"
	filepath "path/filepath"
)

// Notebook binds the topology declared by NotebookManagement to shared layout state.
type Notebook struct {
	core     mgmt.Scope[NotebookLayout]
	Manifest *NotebookManifestDocument
	Readme   *NotebookReadmeDocument
}

func (v *Notebook) Layout() *NotebookLayout { return v.core.Layout() }
func (v *Notebook) Binding() mgmt.Binding   { return v.core.Binding() }
func (v *Notebook) Capabilities() mgmt.Capabilities {
	allowed := map[mgmt.Operation]bool{
		mgmt.Operation("bootstrap"): true,
		mgmt.Operation("inspect"):   true,
		mgmt.Operation("load"):      true,
		mgmt.Operation("save"):      true,
		mgmt.Operation("scaffold"):  true,
		mgmt.Operation("validate"):  true,
	}
	var result mgmt.Capabilities
	for _, op := range v.core.Capabilities() {
		if allowed[op] {
			result = append(result, op)
		}
	}
	return result
}

// BindNotebook retains the supplied composed layout and any cached edits.
func BindNotebook(owner mgmt.Bound, tree *NotebookLayout, options mgmt.ScopeOptions) (*Notebook, error) {
	core, err := mgmt.BindScope(owner, tree, options)
	if err != nil {
		return nil, err
	}
	return wrapNotebook(core)
}
func wrapNotebook(core mgmt.Scope[NotebookLayout]) (*Notebook, error) {
	v := &Notebook{core: core}
	boundManifest, err := mgmt.BindDocument[Manifest](v.core, &v.core.Layout().Manifest, mgmt.DocumentOptions[Manifest]{})
	if err != nil {
		return nil, fmt.Errorf("NotebookManagement.Manifest: %w", err)
	}
	v.Manifest = &NotebookManifestDocument{core: boundManifest}
	boundReadme, err := mgmt.BindDocument[string](v.core, &v.core.Layout().Readme, mgmt.DocumentOptions[string]{})
	if err != nil {
		return nil, fmt.Errorf("NotebookManagement.Readme: %w", err)
	}
	v.Readme = &NotebookReadmeDocument{core: boundReadme}
	return v, nil
}

func (v *Notebook) Bootstrap(ctx context.Context, policy mgmt.BootstrapPolicy) (mgmt.Outcome, error) {
	return mgmt.Bootstrap(ctx, v.core, struct{}{}, mgmt.Initialization[NotebookLayout, struct{}]{}, policy)
}
func (v *Notebook) Inspect(ctx context.Context, policy mgmt.InspectionPolicy) (mgmt.Inventory, error) {
	return v.core.Inspect(ctx, policy)
}
func (v *Notebook) Load(ctx context.Context, policy mgmt.LoadPolicy) (mgmt.Outcome, error) {
	return v.core.Load(ctx, policy)
}
func (v *Notebook) Save(ctx context.Context, policy mgmt.SavePolicy) (mgmt.Outcome, error) {
	return v.core.Save(ctx, policy)
}
func (v *Notebook) Scaffold(ctx context.Context, policy mgmt.ScaffoldPolicy) (mgmt.Outcome, error) {
	return v.core.Scaffold(ctx, policy)
}
func (v *Notebook) Validate(ctx context.Context, policy mgmt.ValidationPolicy) (mgmt.Diagnostics, error) {
	return v.core.Validate(ctx, policy)
}

// NotebookManifestDocument is the declared document handle. Operations delegate to mgmt.
type NotebookManifestDocument struct{ core mgmt.Document[Manifest] }

func (v *NotebookManifestDocument) Binding() mgmt.Binding { return v.core.Binding() }
func (v *NotebookManifestDocument) Capabilities() mgmt.Capabilities {
	allowed := map[mgmt.Operation]bool{
		mgmt.Operation("load"):     true,
		mgmt.Operation("read"):     true,
		mgmt.Operation("save"):     true,
		mgmt.Operation("update"):   true,
		mgmt.Operation("validate"): true,
	}
	var result mgmt.Capabilities
	for _, op := range v.core.Capabilities() {
		if allowed[op] {
			result = append(result, op)
		}
	}
	return result
}
func (v *NotebookManifestDocument) Load(ctx context.Context, policy mgmt.LoadPolicy) (mgmt.Outcome, error) {
	return v.core.Load(ctx, policy)
}
func (v *NotebookManifestDocument) Read(ctx context.Context, policy mgmt.ReadPolicy) (Manifest, error) {
	return v.core.Read(ctx, policy)
}
func (v *NotebookManifestDocument) Save(ctx context.Context, policy mgmt.SavePolicy) (mgmt.Outcome, error) {
	return v.core.Save(ctx, policy)
}
func (v *NotebookManifestDocument) Update(ctx context.Context, edit func(*Manifest) error, policy mgmt.UpdatePolicy) (mgmt.Outcome, error) {
	return v.core.Update(ctx, edit, policy)
}
func (v *NotebookManifestDocument) Validate(ctx context.Context, policy mgmt.ValidationPolicy) (mgmt.Diagnostics, error) {
	return v.core.Validate(ctx, policy)
}

// NotebookReadmeDocument is the declared document handle. Operations delegate to mgmt.
type NotebookReadmeDocument struct{ core mgmt.Document[string] }

func (v *NotebookReadmeDocument) Binding() mgmt.Binding { return v.core.Binding() }
func (v *NotebookReadmeDocument) Capabilities() mgmt.Capabilities {
	allowed := map[mgmt.Operation]bool{
		mgmt.Operation("read"): true,
	}
	var result mgmt.Capabilities
	for _, op := range v.core.Capabilities() {
		if allowed[op] {
			result = append(result, op)
		}
	}
	return result
}
func (v *NotebookReadmeDocument) Read(ctx context.Context, policy mgmt.ReadPolicy) (string, error) {
	return v.core.Read(ctx, policy)
}

// Notes binds the topology declared by NotesManagement to shared layout state.
type Notes struct {
	core      mgmt.Space[NotesLayout]
	Notebooks *NotesNotebooksCollection
}

func (v *Notes) Layout() *NotesLayout  { return v.core.Layout() }
func (v *Notes) Binding() mgmt.Binding { return v.core.Binding() }
func (v *Notes) Capabilities() mgmt.Capabilities {
	allowed := map[mgmt.Operation]bool{
		mgmt.Operation("bootstrap"): true,
		mgmt.Operation("inspect"):   true,
		mgmt.Operation("load"):      true,
		mgmt.Operation("save"):      true,
		mgmt.Operation("scaffold"):  true,
		mgmt.Operation("validate"):  true,
	}
	var result mgmt.Capabilities
	for _, op := range v.core.Capabilities() {
		if allowed[op] {
			result = append(result, op)
		}
	}
	return result
}
func (v *Notes) Root() layout.Dir { return v.core.Root() }

// NewNotes composes a fresh layout once without creating filesystem content.
func NewNotes(root string, options mgmt.SpaceOptions) (*Notes, error) {
	absolute, err := filepath.Abs(root)
	if err != nil {
		return nil, err
	}
	tree := new(NotesLayout)
	if err := layout.Compose(absolute, tree); err != nil {
		return nil, err
	}
	return BindNotes(layout.NewDir(absolute), tree, options)
}

// BindNotes retains the supplied composed layout and any cached edits.
func BindNotes(root layout.Dir, tree *NotesLayout, options mgmt.SpaceOptions) (*Notes, error) {
	core, err := mgmt.BindSpace(root, tree, options)
	if err != nil {
		return nil, err
	}
	return wrapNotes(core)
}
func wrapNotes(core mgmt.Space[NotesLayout]) (*Notes, error) {
	v := &Notes{core: core}
	boundNotebooks, err := mgmt.BindCollection(v.core, &v.core.Layout().Notebooks, mgmt.CollectionOptions{})
	if err != nil {
		return nil, fmt.Errorf("NotesManagement.Notebooks: %w", err)
	}
	v.Notebooks = &NotesNotebooksCollection{core: boundNotebooks}
	return v, nil
}

func (v *Notes) Bootstrap(ctx context.Context, policy mgmt.BootstrapPolicy) (mgmt.Outcome, error) {
	return mgmt.Bootstrap(ctx, v.core.Scope(), struct{}{}, mgmt.Initialization[NotesLayout, struct{}]{}, policy)
}
func (v *Notes) Inspect(ctx context.Context, policy mgmt.InspectionPolicy) (mgmt.Inventory, error) {
	return v.core.Scope().Inspect(ctx, policy)
}
func (v *Notes) Load(ctx context.Context, policy mgmt.LoadPolicy) (mgmt.Outcome, error) {
	return v.core.Scope().Load(ctx, policy)
}
func (v *Notes) Save(ctx context.Context, policy mgmt.SavePolicy) (mgmt.Outcome, error) {
	return v.core.Scope().Save(ctx, policy)
}
func (v *Notes) Scaffold(ctx context.Context, policy mgmt.ScaffoldPolicy) (mgmt.Outcome, error) {
	return v.core.Scope().Scaffold(ctx, policy)
}
func (v *Notes) Validate(ctx context.Context, policy mgmt.ValidationPolicy) (mgmt.Diagnostics, error) {
	return v.core.Scope().Validate(ctx, policy)
}

// NotesNotebooksCollection is the declared collection handle. Operations delegate to mgmt.
type NotesNotebooksCollection struct {
	core mgmt.Collection[NotebookLayout]
}

func (v *NotesNotebooksCollection) Binding() mgmt.Binding { return v.core.Binding() }
func (v *NotesNotebooksCollection) Capabilities() mgmt.Capabilities {
	allowed := map[mgmt.Operation]bool{
		mgmt.Operation("at"):     true,
		mgmt.Operation("create"): true,
		mgmt.Operation("list"):   true,
	}
	var result mgmt.Capabilities
	for _, op := range v.core.Capabilities() {
		if allowed[op] {
			result = append(result, op)
		}
	}
	return result
}
func (v *NotesNotebooksCollection) At(key string, policy mgmt.BindPolicy) (*Notebook, error) {
	core, err := v.core.At(key, policy)
	if err != nil {
		return nil, err
	}
	return wrapNotebook(core)
}

// NotesNotebooksCollectionCreated retains the member handle and partial outcome even when creation fails.
type NotesNotebooksCollectionCreated struct {
	Value   *Notebook
	Outcome mgmt.Outcome
}

func (v *NotesNotebooksCollection) Create(ctx context.Context, key string, input NewNotebook, policy mgmt.CreatePolicy) (NotesNotebooksCollectionCreated, error) {
	created, err := mgmt.Create(ctx, v.core, key, input, NotebookCreation, policy)
	result := NotesNotebooksCollectionCreated{Outcome: created.Outcome}
	if created.Value != nil {
		var bindErr error
		result.Value, bindErr = wrapNotebook(created.Value)
		if bindErr != nil {
			if err != nil {
				return result, fmt.Errorf("creation: %w; binding created member: %w", err, bindErr)
			}
			return result, bindErr
		}
	}
	return result, err
}
func (v *NotesNotebooksCollection) List(ctx context.Context, policy mgmt.ListPolicy) (mgmt.Inventory, error) {
	return v.core.List(ctx, policy)
}
